spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/sequrity
spring.datasource.username=root
spring.datasource.password=abhi10
spring.jpa.hibernate.ddl-auto=update
server.port=8007

spring.jpa.show-sql=true